[package]
name = "sessionManager"
version = "0.1.0"
edition = "2021"

[dependencies]
fuzzy-matcher = "0.3.7"
ratatui = "0.29.0"
serde = {version = "1.0.214", features = ["derive"]}
serde_json = "1.0.132"
